title: Page/Service
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: description
            field:
              type: textarea
              display: Description
          -
            handle: cover_image
            field:
              max_files: 1
              container: assets
              type: assets
              display: 'Cover image'
      -
        display: Content
        fields:
          -
            import: blocks.builder
  meta:
    display: Meta
    sections:
      -
        fields:
          -
            import: utilities.meta
      -
        display: 'Open Graph'
        fields:
          -
            import: utilities.open_graph
      -
        display: Sitemap
        fields:
          -
            import: utilities.sitemap
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - pages
              max_items: 1
              listable: false
              localizable: true
          -
            handle: template
            field:
              type: template
              display: Template
              folder: templates
